# Generated by Django 3.2.16 on 2023-05-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230501_1741'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_username',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_username_following'),
        ),
    ]
